name: Deploy Frontend to Firebase Hosting
on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm install

      - name: Build Angular
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.16.0
        with:
          args: deploy --only hosting --project banckend-tasks
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BANCKEND_TASKS }}
